-- ===================================================================
-- STUDENT SKILL EXCHANGE PLATFORM - SUPABASE POSTGRESQL SCHEMA
-- Project URL: https://qfokonidfrpkunkuivwo.supabase.co
-- Run this script in the Supabase SQL Editor (Dashboard > SQL Editor)
-- ===================================================================

-- 1. USERS TABLE
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'ROLE_STUDENT',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    email_verified BOOLEAN NOT NULL DEFAULT TRUE,
    has_seen_landing BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. STUDENT PROFILES TABLE
CREATE TABLE IF NOT EXISTS public.student_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE REFERENCES public.users(id) ON DELETE CASCADE,
    full_name TEXT NOT NULL,
    email TEXT NOT NULL,
    college TEXT NOT NULL,
    department TEXT NOT NULL,
    year_of_study TEXT NOT NULL,
    phone TEXT,
    bio TEXT,
    avatar_url TEXT,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    average_rating NUMERIC(3,2) NOT NULL DEFAULT 0.00,
    completed_exchanges_count INT NOT NULL DEFAULT 0,
    is_blocked BOOLEAN NOT NULL DEFAULT FALSE
);

-- 3. SKILL CATEGORIES TABLE
CREATE TABLE IF NOT EXISTS public.skill_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    icon TEXT
);

-- 4. SKILLS TABLE
CREATE TABLE IF NOT EXISTS public.skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    category_id BIGINT NOT NULL REFERENCES public.skill_categories(id) ON DELETE CASCADE,
    category_name TEXT,
    description TEXT
);

-- 5. USER TEACHING SKILLS TABLE
CREATE TABLE IF NOT EXISTS public.user_teaching_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
    skill_name TEXT,
    category_id BIGINT,
    category_name TEXT,
    proficiency_level TEXT DEFAULT 'Intermediate',
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verification_status TEXT DEFAULT 'NOT_VERIFIED',
    proof_document_url TEXT,
    verification_notes TEXT,
    CONSTRAINT uk_user_teaching UNIQUE (user_id, skill_id)
);

-- 6. USER LEARNING SKILLS TABLE
CREATE TABLE IF NOT EXISTS public.user_learning_skills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    skill_id BIGINT NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
    skill_name TEXT,
    category_id BIGINT,
    category_name TEXT,
    urgency_level TEXT DEFAULT 'Medium',
    notes TEXT,
    CONSTRAINT uk_user_learning UNIQUE (user_id, skill_id)
);

-- 7. PROJECTS TABLE
CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    technologies TEXT,
    link TEXT,
    proof_url TEXT
);

-- 8. EXPERIENCES TABLE
CREATE TABLE IF NOT EXISTS public.experiences (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    organization TEXT,
    description TEXT,
    duration TEXT,
    start_date TEXT,
    end_date TEXT,
    is_current BOOLEAN DEFAULT FALSE
);

-- 9. EXCHANGE REQUESTS TABLE
CREATE TABLE IF NOT EXISTS public.exchange_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    sender_name TEXT,
    sender_email TEXT,
    receiver_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    receiver_name TEXT,
    skill_offered_id BIGINT NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
    skill_offered_name TEXT,
    skill_requested_id BIGINT NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
    skill_requested_name TEXT,
    message TEXT,
    learning_mode TEXT NOT NULL DEFAULT 'ONLINE',
    status TEXT NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 10. EXCHANGES TABLE
CREATE TABLE IF NOT EXISTS public.exchanges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id BIGINT NOT NULL UNIQUE REFERENCES public.exchange_requests(id) ON DELETE CASCADE,
    student1_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    student1_name TEXT,
    student2_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    student2_name TEXT,
    user_a_id BIGINT,
    user_a_name TEXT,
    user_b_id BIGINT,
    user_b_name TEXT,
    skill1_id BIGINT NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
    skill1_name TEXT,
    skill2_id BIGINT NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
    skill2_name TEXT,
    skill_offered_title TEXT,
    skill_requested_title TEXT,
    learning_mode TEXT NOT NULL DEFAULT 'ONLINE',
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    start_date TIMESTAMPTZ DEFAULT NOW(),
    completion_date TIMESTAMPTZ
);

-- 11. MESSAGES TABLE
CREATE TABLE IF NOT EXISTS public.messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    sender_name TEXT,
    receiver_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    receiver_name TEXT,
    message_text TEXT NOT NULL,
    sent_at TIMESTAMPTZ DEFAULT NOW(),
    delivered_at TIMESTAMPTZ,
    seen_at TIMESTAMPTZ,
    status TEXT DEFAULT 'SENT',
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    attachment_url TEXT,
    attachment_type TEXT,
    attachment_name TEXT,
    attachment_size BIGINT,
    reply_to JSONB
);

-- 12. NOTIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 13. SKILL VERIFICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.skill_verifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    student_name TEXT,
    student_email TEXT,
    skill_id BIGINT NOT NULL REFERENCES public.skills(id) ON DELETE CASCADE,
    skill_name TEXT,
    certificate_name TEXT,
    certificate_url TEXT,
    project_title TEXT,
    project_description TEXT,
    project_technologies TEXT,
    project_link TEXT,
    project_proof_url TEXT,
    experience_title TEXT,
    experience_organization TEXT,
    experience_description TEXT,
    experience_duration TEXT,
    experience_start_date TEXT,
    experience_end_date TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    admin_comment TEXT,
    submission_date TIMESTAMPTZ DEFAULT NOW(),
    reviewed_date TIMESTAMPTZ
);

-- 14. RATINGS & REVIEWS TABLE
CREATE TABLE IF NOT EXISTS public.reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange_id BIGINT NOT NULL REFERENCES public.exchanges(id) ON DELETE CASCADE,
    reviewer_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    reviewer_name TEXT,
    reviewed_student_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    reviewed_student_name TEXT,
    rating INT NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uk_review_exchange_reviewer UNIQUE (exchange_id, reviewer_id)
);

-- 15. REPORTS TABLE
CREATE TABLE IF NOT EXISTS public.reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    reported_user_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    reason TEXT NOT NULL,
    description TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    admin_notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 16. BLOCKED USERS TABLE
CREATE TABLE IF NOT EXISTS public.blocked_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    blocker_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    blocked_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    blocked_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT uk_blocker_blocked UNIQUE (blocker_id, blocked_id)
);

-- 17. AUDIT LOGS TABLE
CREATE TABLE IF NOT EXISTS public.audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    performed_by TEXT NOT NULL,
    target TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT NOW(),
    details TEXT
);

-- 18. OTPS TABLE
CREATE TABLE IF NOT EXISTS public.otps (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL,
    otp_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    purpose TEXT NOT NULL DEFAULT 'VERIFY',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 19. ONLINE SESSIONS TABLE
CREATE TABLE IF NOT EXISTS public.online_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange_request_id BIGINT REFERENCES public.exchange_requests(id) ON DELETE SET NULL,
    exchange_id BIGINT REFERENCES public.exchanges(id) ON DELETE SET NULL,
    title TEXT NOT NULL,
    skill_id BIGINT REFERENCES public.skills(id) ON DELETE SET NULL,
    skill_name TEXT,
    teacher_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    teacher_name TEXT,
    teacher_email TEXT,
    learner_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    learner_name TEXT,
    learner_email TEXT,
    scheduled_date TEXT,
    scheduled_time TEXT,
    scheduled_at TIMESTAMPTZ,
    duration_minutes INT DEFAULT 60,
    description TEXT,
    zoom_meeting_id TEXT,
    zoom_join_url TEXT,
    zoom_password TEXT,
    status TEXT NOT NULL DEFAULT 'Scheduled',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 20. EXCHANGE NOTES TABLE
CREATE TABLE IF NOT EXISTS public.exchange_notes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    student_name TEXT,
    partner_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    partner_name TEXT,
    exchange_request_id BIGINT REFERENCES public.exchange_requests(id) ON DELETE SET NULL,
    topic TEXT NOT NULL,
    content TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 21. OFFLINE PROGRESS TABLE
CREATE TABLE IF NOT EXISTS public.offline_progress (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    exchange_request_id BIGINT REFERENCES public.exchange_requests(id) ON DELETE SET NULL,
    exchange_id BIGINT REFERENCES public.exchanges(id) ON DELETE SET NULL,
    teacher_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    teacher_name TEXT,
    teacher_email TEXT,
    learner_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    learner_name TEXT,
    learner_email TEXT,
    skill_offered_title TEXT,
    skill_requested_title TEXT,
    learning_mode TEXT NOT NULL DEFAULT 'OFFLINE',
    location TEXT,
    start_date TIMESTAMPTZ,
    expected_completion_date TIMESTAMPTZ,
    progress_percentage INT DEFAULT 0,
    current_stage TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    completion_date TIMESTAMPTZ,
    last_activity_at TIMESTAMPTZ DEFAULT NOW(),
    next_activity TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 22. OFFLINE UPDATES TABLE
CREATE TABLE IF NOT EXISTS public.offline_updates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offline_exchange_progress_id BIGINT NOT NULL REFERENCES public.offline_progress(id) ON DELETE CASCADE,
    submitted_by_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    submitted_by_name TEXT,
    session_date TEXT,
    stage TEXT,
    topics_covered TEXT,
    description TEXT,
    progress_percentage INT,
    next_activity TEXT,
    attachment_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 23. KITAB BHANDAR TABLE
CREATE TABLE IF NOT EXISTS public.kitab_bhandar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    author TEXT,
    category TEXT,
    condition TEXT,
    owner_id BIGINT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
    owner_name TEXT,
    owner_email TEXT,
    department TEXT,
    barter_for TEXT,
    status TEXT NOT NULL DEFAULT 'AVAILABLE',
    image_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ===================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- Enabling RLS with open policies for full server / anon access
-- ===================================================================

DO $$
DECLARE
    t text;
BEGIN
    FOR t IN
        SELECT table_name
        FROM information_schema.tables
        WHERE table_schema = 'public'
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
        EXECUTE format('DROP POLICY IF EXISTS "Public access policy" ON public.%I;', t);
        EXECUTE format('CREATE POLICY "Public access policy" ON public.%I FOR ALL USING (true) WITH CHECK (true);', t);
    END LOOP;
END $$;

-- ===================================================================
-- INITIAL PRE-SEEDED DEMONSTRATION DATA
-- ===================================================================

-- Categories
INSERT INTO public.skill_categories (id, name, description, icon) VALUES
(1, 'Programming', 'Software engineering, algorithms & coding', 'bi-code-slash'),
(2, 'Web Development', 'Frontend, backend, and full-stack web tech', 'bi-globe'),
(3, 'Design', 'Graphic design, UI/UX, and branding', 'bi-palette'),
(4, 'Photography & Video', 'Digital photography & video post-production', 'bi-camera-video'),
(5, 'Communication', 'Public speaking, presentation, & soft skills', 'bi-chat-dots'),
(6, 'Academic & Productivity', 'Mathematics, data analysis, and tools', 'bi-journal-bookmark')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, description = EXCLUDED.description, icon = EXCLUDED.icon;

-- Skills
INSERT INTO public.skills (id, name, category_id, category_name, description) VALUES
(1, 'Java', 1, 'Programming', 'Core Java OOP, Collections, Multi-threading, and Spring Boot framework'),
(2, 'Python', 1, 'Programming', 'Python scripting, data structures, and automation'),
(3, 'HTML/CSS/JS', 2, 'Web Development', 'Modern responsive web development with JavaScript and Bootstrap 5'),
(4, 'Photoshop', 3, 'Design', 'Image manipulation, digital art, poster design, and photo editing'),
(5, 'Graphic Design', 3, 'Design', 'Typography, Figma UI design, and visual brand identity'),
(6, 'Video Editing', 4, 'Photography & Video', 'Premiere Pro / DaVinci Resolve video cutting and color grading'),
(7, 'Public Speaking', 5, 'Communication', 'Overcoming stage fear, debate, and confident speech presentation'),
(8, 'Excel & Data Analysis', 6, 'Academic & Productivity', 'Formulas, pivot tables, lookup functions, and data charts')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, category_id = EXCLUDED.category_id, description = EXCLUDED.description;

-- Users
INSERT INTO public.users (id, email, password, role, active, email_verified, has_seen_landing) VALUES
(1, 'admin@mgmmumbai.ac.in', 'password123', 'ROLE_ADMIN', TRUE, TRUE, TRUE),
(2, 'harsh@mgmmumbai.ac.in', 'password123', 'ROLE_STUDENT', TRUE, TRUE, TRUE),
(3, 'sejal@mgmmumbai.ac.in', 'password123', 'ROLE_STUDENT', TRUE, TRUE, TRUE),
(4, 'raza@mgmmumbai.ac.in', 'password123', 'ROLE_STUDENT', TRUE, TRUE, TRUE),
(5, 'udipti@mgmmumbai.ac.in', 'password123', 'ROLE_STUDENT', TRUE, TRUE, TRUE)
ON CONFLICT (id) DO UPDATE SET email = EXCLUDED.email, password = EXCLUDED.password, role = EXCLUDED.role;

-- Profiles
INSERT INTO public.student_profiles (id, user_id, full_name, email, college, department, year_of_study, phone, bio, avatar_url, is_verified, average_rating, completed_exchanges_count, is_blocked) VALUES
(2, 2, 'Harsh Vardhan', 'harsh@mgmmumbai.ac.in', 'College of Engineering & Technology', 'Information Technology', '2nd Year', '9876543210', '2nd-year IT student passionate about Java backend architectures and algorithms. Wanting to learn design and video editing!', 'https://api.dicebear.com/7.x/bottts/svg?seed=Harsh', TRUE, 4.80, 2, FALSE),
(3, 3, 'Sejal Sharma', 'sejal@mgmmumbai.ac.in', 'College of Engineering & Technology', 'Information Technology', '2nd Year', '9876543211', 'Creative designer and IT student. Certified in Adobe Photoshop. Looking to conquer core Java and web development!', 'https://api.dicebear.com/7.x/bottts/svg?seed=Sejal', TRUE, 4.90, 3, FALSE),
(4, 4, 'Raza Khan', 'raza@mgmmumbai.ac.in', 'College of Engineering & Technology', 'Computer Science', '3rd Year', '9876543212', 'Python enthusiast and data geek. Wanting to improve communication and speech delivery for campus placements.', 'https://api.dicebear.com/7.x/bottts/svg?seed=Raza', FALSE, 4.50, 1, FALSE),
(5, 5, 'Udipti Sen', 'udipti@mgmmumbai.ac.in', 'College of Engineering & Technology', 'Information Technology', '2nd Year', '9876543213', 'College debate society president. Eager to help peers with confident public speaking in return for Python tutoring!', 'https://api.dicebear.com/7.x/bottts/svg?seed=Udipti', TRUE, 5.00, 4, FALSE)
ON CONFLICT (id) DO UPDATE SET full_name = EXCLUDED.full_name, bio = EXCLUDED.bio, average_rating = EXCLUDED.average_rating;

-- Teaching Skills
INSERT INTO public.user_teaching_skills (id, user_id, skill_id, skill_name, category_id, category_name, proficiency_level, is_verified, verification_status, proof_document_url) VALUES
(1, 2, 1, 'Java', 1, 'Programming', 'Advanced', TRUE, 'VERIFIED', 'uploads/certificates/harsh_java.pdf'),
(2, 2, 3, 'HTML/CSS/JS', 2, 'Web Development', 'Intermediate', FALSE, 'NOT_VERIFIED', NULL),
(3, 3, 4, 'Photoshop', 3, 'Design', 'Expert', TRUE, 'VERIFIED', 'uploads/certificates/sejal_photoshop.pdf'),
(4, 3, 5, 'Graphic Design', 3, 'Design', 'Advanced', FALSE, 'NEEDS_RESUBMISSION', NULL),
(5, 4, 2, 'Python', 1, 'Programming', 'Advanced', FALSE, 'PENDING', NULL),
(6, 4, 8, 'Excel & Data Analysis', 6, 'Academic & Productivity', 'Intermediate', FALSE, 'NOT_VERIFIED', NULL),
(7, 5, 7, 'Public Speaking', 5, 'Communication', 'Expert', TRUE, 'VERIFIED', 'uploads/certificates/debate.pdf')
ON CONFLICT (id) DO UPDATE SET proficiency_level = EXCLUDED.proficiency_level, is_verified = EXCLUDED.is_verified;

-- Learning Skills
INSERT INTO public.user_learning_skills (id, user_id, skill_id, skill_name, category_id, category_name, urgency_level) VALUES
(1, 2, 4, 'Photoshop', 3, 'Design', 'High'),
(2, 2, 6, 'Video Editing', 4, 'Photography & Video', 'Medium'),
(3, 3, 1, 'Java', 1, 'Programming', 'High'),
(4, 3, 3, 'HTML/CSS/JS', 2, 'Web Development', 'Medium'),
(5, 4, 7, 'Public Speaking', 5, 'Communication', 'High'),
(6, 5, 2, 'Python', 1, 'Programming', 'High'),
(7, 5, 8, 'Excel & Data Analysis', 6, 'Academic & Productivity', 'Medium')
ON CONFLICT (id) DO UPDATE SET urgency_level = EXCLUDED.urgency_level;

-- Projects
INSERT INTO public.projects (id, student_id, title, description, technologies, link, proof_url) VALUES
(1, 2, 'Microservices Learning Exchange Backend', 'Developed a distributed RESTful skill exchange engine with Spring Boot, Redis caching, and reciprocal matchmaking.', 'Java 17, Spring Boot, MySQL, Docker', 'https://github.com/harsh/skill-exchange-service', ''),
(2, 2, 'College Campus Event Manager', 'Built a real-time event booking and QR attendance scanning portal for MGM annual technical fests.', 'Java, Spring MVC, Thymeleaf, PostgreSQL', 'https://github.com/harsh/mgm-event-manager', ''),
(3, 3, 'Brand Identity & Vector Retouching System', 'Created commercial posters, photo composite imagery, and multi-layered branding assets for college cultural fests.', 'Adobe Photoshop 2024, Lightroom, Figma', 'https://behance.net/sejal_photoshop_portfolio', '')
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title;

-- Experiences
INSERT INTO public.experiences (id, student_id, title, organization, description, duration, start_date, end_date, is_current) VALUES
(1, 2, 'Lead Java Developer & Mentor', 'MGM College Open Source Developer Club', 'Mentored 40+ junior students in Object-Oriented Programming, Spring framework fundamentals, and code reviews.', '1 Year', '2025-01-10', 'Present', TRUE),
(2, 3, 'Head Graphic Designer', 'MGM College Annual Magazine Editorial Board', 'Designed front-cover layouts, retouched photography, and coordinated print publishing for 1,500+ physical magazine copies.', '1.5 Years', '2024-09-01', 'Present', TRUE)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title;

-- Exchange Requests
INSERT INTO public.exchange_requests (id, sender_id, sender_name, sender_email, receiver_id, receiver_name, skill_offered_id, skill_offered_name, skill_requested_id, skill_requested_name, message, learning_mode, status) VALUES
(1, 2, 'Harsh Vardhan', 'harsh@mgmmumbai.ac.in', 3, 'Sejal Sharma', 1, 'Java', 4, 'Photoshop', 'Hey Sejal! Let''s trade Java OOP lessons for Photoshop UI poster design!', 'ONLINE', 'COMPLETED'),
(2, 4, 'Raza Khan', 'raza@mgmmumbai.ac.in', 5, 'Udipti Sen', 2, 'Python', 7, 'Public Speaking', 'Hi Udipti! I can teach you Python basics in exchange for speech coaching.', 'CHAT', 'ACCEPTED'),
(3, 3, 'Sejal Sharma', 'sejal@mgmmumbai.ac.in', 2, 'Harsh Vardhan', 5, 'Graphic Design', 3, 'HTML/CSS/JS', 'Hi Harsh! Want to explore Figma design while teaching me modern CSS layouts?', 'ONLINE', 'PENDING')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status;

-- Exchanges
INSERT INTO public.exchanges (id, request_id, student1_id, student1_name, student2_id, student2_name, user_a_id, user_a_name, user_b_id, user_b_name, skill1_id, skill1_name, skill2_id, skill2_name, skill_offered_title, skill_requested_title, learning_mode, status) VALUES
(1, 1, 2, 'Harsh Vardhan', 3, 'Sejal Sharma', 2, 'Harsh Vardhan', 3, 'Sejal Sharma', 1, 'Java', 4, 'Photoshop', 'Java', 'Photoshop', 'ONLINE', 'COMPLETED'),
(2, 2, 4, 'Raza Khan', 5, 'Udipti Sen', 4, 'Raza Khan', 5, 'Udipti Sen', 2, 'Python', 7, 'Public Speaking', 'Python', 'Public Speaking', 'CHAT', 'ACTIVE')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status;

-- Reviews
INSERT INTO public.reviews (id, exchange_id, reviewer_id, reviewer_name, reviewed_student_id, reviewed_student_name, rating, comment) VALUES
(1, 1, 3, 'Sejal Sharma', 2, 'Harsh Vardhan', 5, 'Harsh was phenomenal at explaining Java OOP principles and Spring fundamentals! Very articulate and helpful.'),
(2, 1, 2, 'Harsh Vardhan', 3, 'Sejal Sharma', 5, 'Sejal is a Photoshop wizard! She guided me step-by-step through layers, retouching, and export formats.')
ON CONFLICT (id) DO UPDATE SET rating = EXCLUDED.rating, comment = EXCLUDED.comment;

-- Skill Verifications
INSERT INTO public.skill_verifications (id, student_id, student_name, student_email, skill_id, skill_name, certificate_name, certificate_url, project_title, project_description, project_technologies, project_link, project_proof_url, experience_title, experience_organization, experience_description, experience_duration, experience_start_date, experience_end_date, status, admin_comment) VALUES
(1, 4, 'Raza Khan', 'raza@mgmmumbai.ac.in', 2, 'Python', 'HackerRank Python 5-Star Gold Badge', 'uploads/verifications/raza_python.pdf', 'Automated Data Scraping & Analysis Pipeline', 'Built a Python-based asynchronous web scraper and pandas analysis pipeline processing 10,000+ records daily with data cleaning and CSV export.', 'Python 3.11, BeautifulSoup4, Pandas, SQLite, Requests', 'https://github.com/raza-khan/python-data-pipeline', 'uploads/proofs/raza_pipeline_screenshot.png', 'Lead Python Developer & Workshop Trainer', 'MGM Coding Club & Techfest Committee', 'Conducted hands-on Python workshops for 80+ engineering students, built the campus competition scoring system, and reviewed peer code.', '8 months', '2025-08-01', 'Present', 'PENDING', ''),
(2, 2, 'Harsh Vardhan', 'harsh@mgmmumbai.ac.in', 1, 'Java', 'Oracle Certified Associate Java SE 11', 'uploads/certificates/harsh_java.pdf', 'Enterprise Spring Boot Microservices Platform', 'Architected RESTful microservices with Spring Data JPA, JWT authentication, and MySQL backend with 95%+ unit test coverage.', 'Java 17, Spring Boot, Hibernate, MySQL, Maven, Docker', 'https://github.com/harsh4505/enterprise-java-suite', 'uploads/proofs/harsh_spring_demo.png', 'Backend Engineering Teaching Assistant', 'MGM Department of Information Technology', 'Assisted professors in evaluating Java OOP laboratory assignments and conducted weekly tutorial sessions for 60+ sophomores.', '1 year', '2025-07-01', 'Present', 'VERIFIED', 'Outstanding project portfolio and validated departmental teaching experience.'),
(3, 3, 'Sejal Sharma', 'sejal@mgmmumbai.ac.in', 4, 'Photoshop', 'Adobe Certified Professional in Visual Design', 'uploads/certificates/sejal_photoshop.pdf', 'Brand Identity & Vector Retouching System', 'Created high-resolution commercial posters, photo composite imagery, and multi-layered branding assets for college cultural fests.', 'Adobe Photoshop 2024, Lightroom, Camera RAW', 'https://behance.net/sejal_photoshop_portfolio', 'uploads/proofs/sejal_brand_suite.png', 'Head Graphic Designer', 'MGM College Annual Magazine Editorial Board', 'Designed front-cover layouts, retouched photography, and coordinated with printers for 1,500+ physical magazine copies.', '1.5 years', '2024-09-01', 'Present', 'VERIFIED', 'High caliber creative portfolio with confirmed publication track record.')
ON CONFLICT (id) DO UPDATE SET status = EXCLUDED.status;

-- Messages
INSERT INTO public.messages (id, sender_id, sender_name, receiver_id, receiver_name, message_text, status, is_read) VALUES
(1, 2, 'Harsh Vardhan', 3, 'Sejal Sharma', 'Hi Sejal! Thanks for accepting my Java for Photoshop request!', 'SEEN', TRUE),
(2, 3, 'Sejal Sharma', 2, 'Harsh Vardhan', 'Hey Harsh! Super excited! When are you free for our first session?', 'SEEN', TRUE),
(3, 2, 'Harsh Vardhan', 3, 'Sejal Sharma', 'I''m free tomorrow after 5 PM in the college library or over Google Meet!', 'SEEN', TRUE)
ON CONFLICT (id) DO UPDATE SET message_text = EXCLUDED.message_text;

-- Notifications
INSERT INTO public.notifications (id, recipient_id, title, message, type, is_read) VALUES
(1, 2, 'Welcome to Skill Exchange!', 'Start by exploring student matches or adding skills you teach and want to learn.', 'INFO', TRUE),
(2, 2, 'Incoming Proposal from Sejal', 'Sejal Sharma proposed an exchange: Offering Graphic Design for HTML/CSS/JS.', 'EXCHANGE_REQUEST', FALSE)
ON CONFLICT (id) DO UPDATE SET title = EXCLUDED.title;

-- Audit Logs
INSERT INTO public.audit_logs (id, action, performed_by, target, details) VALUES
(1, 'PLATFORM_INIT', 'admin@mgmmumbai.ac.in', 'SYSTEM', 'Platform initialized with Supabase cloud PostgreSQL storage and college email security policy (@mgmmumbai.ac.in).')
ON CONFLICT (id) DO NOTHING;

-- Reset Identity Sequences
SELECT setval(pg_get_serial_sequence('public.users', 'id'), coalesce(max(id), 0) + 1, false) FROM public.users;
SELECT setval(pg_get_serial_sequence('public.student_profiles', 'id'), coalesce(max(id), 0) + 1, false) FROM public.student_profiles;
SELECT setval(pg_get_serial_sequence('public.skill_categories', 'id'), coalesce(max(id), 0) + 1, false) FROM public.skill_categories;
SELECT setval(pg_get_serial_sequence('public.skills', 'id'), coalesce(max(id), 0) + 1, false) FROM public.skills;
SELECT setval(pg_get_serial_sequence('public.user_teaching_skills', 'id'), coalesce(max(id), 0) + 1, false) FROM public.user_teaching_skills;
SELECT setval(pg_get_serial_sequence('public.user_learning_skills', 'id'), coalesce(max(id), 0) + 1, false) FROM public.user_learning_skills;
SELECT setval(pg_get_serial_sequence('public.projects', 'id'), coalesce(max(id), 0) + 1, false) FROM public.projects;
SELECT setval(pg_get_serial_sequence('public.experiences', 'id'), coalesce(max(id), 0) + 1, false) FROM public.experiences;
SELECT setval(pg_get_serial_sequence('public.exchange_requests', 'id'), coalesce(max(id), 0) + 1, false) FROM public.exchange_requests;
SELECT setval(pg_get_serial_sequence('public.exchanges', 'id'), coalesce(max(id), 0) + 1, false) FROM public.exchanges;
SELECT setval(pg_get_serial_sequence('public.messages', 'id'), coalesce(max(id), 0) + 1, false) FROM public.messages;
SELECT setval(pg_get_serial_sequence('public.notifications', 'id'), coalesce(max(id), 0) + 1, false) FROM public.notifications;
SELECT setval(pg_get_serial_sequence('public.skill_verifications', 'id'), coalesce(max(id), 0) + 1, false) FROM public.skill_verifications;
SELECT setval(pg_get_serial_sequence('public.reviews', 'id'), coalesce(max(id), 0) + 1, false) FROM public.reviews;
SELECT setval(pg_get_serial_sequence('public.reports', 'id'), coalesce(max(id), 0) + 1, false) FROM public.reports;
SELECT setval(pg_get_serial_sequence('public.blocked_users', 'id'), coalesce(max(id), 0) + 1, false) FROM public.blocked_users;
SELECT setval(pg_get_serial_sequence('public.audit_logs', 'id'), coalesce(max(id), 0) + 1, false) FROM public.audit_logs;
SELECT setval(pg_get_serial_sequence('public.otps', 'id'), coalesce(max(id), 0) + 1, false) FROM public.otps;
SELECT setval(pg_get_serial_sequence('public.online_sessions', 'id'), coalesce(max(id), 0) + 1, false) FROM public.online_sessions;
SELECT setval(pg_get_serial_sequence('public.exchange_notes', 'id'), coalesce(max(id), 0) + 1, false) FROM public.exchange_notes;
SELECT setval(pg_get_serial_sequence('public.offline_progress', 'id'), coalesce(max(id), 0) + 1, false) FROM public.offline_progress;
SELECT setval(pg_get_serial_sequence('public.offline_updates', 'id'), coalesce(max(id), 0) + 1, false) FROM public.offline_updates;
SELECT setval(pg_get_serial_sequence('public.kitab_bhandar', 'id'), coalesce(max(id), 0) + 1, false) FROM public.kitab_bhandar;

